package com.google.android.gms.internal;

import android.content.Context;
import android.support.v4.view.GravityCompat;
import com.appboy.Constants;
import com.etsy.android.lib.requests.EtsyRequest;
import com.google.android.gms.ads.internal.C1101o;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.apache.commons.lang3.StringUtils;

@jw
public final class dz {
    public static final dv<String> f4801A;
    public static final dv<Boolean> f4802B;
    public static final dv<Boolean> f4803C;
    public static final dv<Boolean> f4804D;
    public static final dv<String> f4805E;
    public static final dv<String> f4806F;
    public static final dv<String> f4807G;
    public static final dv<Boolean> f4808H;
    public static final dv<String> f4809I;
    public static final dv<Boolean> f4810J;
    public static final dv<Boolean> f4811K;
    public static final dv<Integer> f4812L;
    public static final dv<Integer> f4813M;
    public static final dv<Integer> f4814N;
    public static final dv<Integer> f4815O;
    public static final dv<Integer> f4816P;
    public static final dv<Boolean> f4817Q;
    public static final dv<Boolean> f4818R;
    public static final dv<Long> f4819S;
    public static final dv<String> f4820T;
    public static final dv<String> f4821U;
    public static final dv<Boolean> f4822V;
    public static final dv<Boolean> f4823W;
    public static final dv<Boolean> f4824X;
    public static final dv<String> f4825Y;
    public static final dv<Boolean> f4826Z;
    public static final dv<String> f4827a;
    public static final dv<Boolean> aA;
    public static final dv<Boolean> aB;
    public static final dv<Boolean> aC;
    public static final dv<Boolean> aD;
    public static final dv<Boolean> aE;
    public static final dv<String> aF;
    public static final dv<Long> aG;
    public static final dv<Boolean> aH;
    public static final dv<Boolean> aI;
    public static final dv<Long> aJ;
    public static final dv<Long> aK;
    public static final dv<Boolean> aL;
    public static final dv<Long> aM;
    public static final dv<String> aN;
    public static final dv<Boolean> aO;
    public static final dv<String> aP;
    public static final dv<Boolean> aQ;
    public static final dv<Boolean> aR;
    public static final dv<String> aS;
    public static final dv<Boolean> aT;
    public static final dv<Boolean> aU;
    public static final dv<String> aV;
    public static final dv<Boolean> aW;
    public static final dv<Boolean> aX;
    public static final dv<Boolean> aY;
    public static final dv<Boolean> aZ;
    public static final dv<Boolean> aa;
    public static final dv<Integer> ab;
    public static final dv<Boolean> ac;
    public static final dv<String> ad;
    public static final dv<String> ae;
    public static final dv<String> af;
    public static final dv<Boolean> ag;
    public static final dv<Boolean> ah;
    public static final dv<Boolean> ai;
    public static final dv<String> aj;
    public static final dv<String> ak;
    public static final dv<Integer> al;
    public static final dv<Integer> am;
    public static final dv<Integer> an;
    public static final dv<String> ao;
    public static final dv<String> ap;
    public static final dv<String> aq;
    public static final dv<String> ar;
    public static final dv<Boolean> as;
    public static final dv<Boolean> at;
    public static final dv<String> au;
    public static final dv<Boolean> av;
    public static final dv<Long> aw;
    public static final dv<Boolean> ax;
    public static final dv<Boolean> ay;
    public static final dv<Boolean> az;
    public static final dv<String> f4828b;
    public static final dv<String> bA;
    public static final dv<String> bB;
    public static final dv<Long> bC;
    public static final dv<Boolean> bD;
    public static final dv<Boolean> bE;
    public static final dv<Boolean> bF;
    public static final dv<Boolean> bG;
    public static final dv<String> bH;
    public static final dv<String> bI;
    public static final dv<Long> bJ;
    public static final dv<String> bK;
    public static final dv<Boolean> bL;
    public static final dv<Boolean> bM;
    public static final dv<Boolean> ba;
    public static final dv<Boolean> bb;
    public static final dv<Boolean> bc;
    public static final dv<String> bd;
    public static final dv<Long> be;
    public static final dv<Boolean> bf;
    public static final dv<Boolean> bg;
    public static final dv<String> bh;
    public static final dv<Boolean> bi;
    public static final dv<Long> bj;
    public static final dv<Integer> bk;
    public static final dv<Integer> bl;
    public static final dv<Boolean> bm;
    public static final dv<String> bn;
    public static final dv<Long> bo;
    public static final dv<String> bp;
    public static final dv<Long> bq;
    public static final dv<String> br;
    public static final dv<Boolean> bs;
    public static final dv<String> bt;
    public static final dv<Long> bu;
    public static final dv<String> bv;
    public static final dv<String> bw;
    public static final dv<String> bx;
    public static final dv<String> by;
    public static final dv<String> bz;
    public static final dv<Boolean> f4829c;
    public static final dv<String> f4830d;
    public static final dv<Boolean> f4831e;
    public static final dv<String> f4832f;
    public static final dv<Boolean> f4833g;
    public static final dv<Boolean> f4834h;
    public static final dv<String> f4835i;
    public static final dv<Boolean> f4836j;
    public static final dv<String> f4837k;
    public static final dv<String> f4838l;
    public static final dv<String> f4839m;
    public static final dv<Boolean> f4840n;
    public static final dv<String> f4841o;
    public static final dv<Integer> f4842p;
    public static final dv<Integer> f4843q;
    public static final dv<Integer> f4844r;
    public static final dv<Long> f4845s;
    public static final dv<Long> f4846t;
    public static final dv<Integer> f4847u;
    public static final dv<Boolean> f4848v;
    public static final dv<String> f4849w;
    public static final dv<Long> f4850x;
    public static final dv<String> f4851y;
    public static final dv<Boolean> f4852z;

    static {
        f4827a = dv.m6424a(0, "gads:sdk_core_experiment_id");
        f4828b = dv.m6428a(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
        f4829c = dv.m6427a(0, "gads:request_builder:singleton_webview", Boolean.valueOf(false));
        f4830d = dv.m6424a(0, "gads:request_builder:singleton_webview_experiment_id");
        f4831e = dv.m6427a(0, "gads:sdk_use_dynamic_module", Boolean.valueOf(true));
        f4832f = dv.m6424a(0, "gads:sdk_use_dynamic_module_experiment_id");
        f4833g = dv.m6427a(0, "gads:sdk_crash_report_enabled", Boolean.valueOf(false));
        f4834h = dv.m6427a(0, "gads:sdk_crash_report_full_stacktrace", Boolean.valueOf(false));
        f4835i = dv.m6428a(0, "gads:sdk_crash_report_class_prefix", "com.google.");
        f4836j = dv.m6427a(0, "gads:block_autoclicks", Boolean.valueOf(false));
        f4837k = dv.m6424a(0, "gads:block_autoclicks_experiment_id");
        f4838l = dv.m6429b(0, "gads:prefetch:experiment_id");
        f4839m = dv.m6424a(0, "gads:spam_app_context:experiment_id");
        f4840n = dv.m6427a(0, "gads:spam_app_context:enabled", Boolean.valueOf(false));
        f4841o = dv.m6424a(0, "gads:video_stream_cache:experiment_id");
        f4842p = dv.m6425a(0, "gads:video_stream_cache:limit_count", 5);
        f4843q = dv.m6425a(0, "gads:video_stream_cache:limit_space", (int) GravityCompat.RELATIVE_LAYOUT_DIRECTION);
        f4844r = dv.m6425a(0, "gads:video_stream_exo_cache:buffer_size", (int) GravityCompat.RELATIVE_LAYOUT_DIRECTION);
        f4845s = dv.m6426a(0, "gads:video_stream_cache:limit_time_sec", 300);
        f4846t = dv.m6426a(0, "gads:video_stream_cache:notify_interval_millis", 1000);
        f4847u = dv.m6425a(0, "gads:video_stream_cache:connect_timeout_millis", (int) EtsyRequest.DEFAULT_TIMEOUT);
        f4848v = dv.m6427a(0, "gads:video:metric_reporting_enabled", Boolean.valueOf(false));
        f4849w = dv.m6428a(0, "gads:video:metric_frame_hash_times", StringUtils.EMPTY);
        f4850x = dv.m6426a(0, "gads:video:metric_frame_hash_time_leniency", 500);
        f4851y = dv.m6429b(0, "gads:spam_ad_id_decorator:experiment_id");
        f4852z = dv.m6427a(0, "gads:spam_ad_id_decorator:enabled", Boolean.valueOf(false));
        f4801A = dv.m6429b(0, "gads:looper_for_gms_client:experiment_id");
        f4802B = dv.m6427a(0, "gads:looper_for_gms_client:enabled", Boolean.valueOf(true));
        f4803C = dv.m6427a(0, "gads:sw_ad_request_service:enabled", Boolean.valueOf(true));
        f4804D = dv.m6427a(0, "gads:sw_dynamite:enabled", Boolean.valueOf(true));
        f4805E = dv.m6428a(0, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
        f4806F = dv.m6428a(0, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
        f4807G = dv.m6428a(0, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
        f4808H = dv.m6427a(0, "gads:enabled_sdk_csi", Boolean.valueOf(false));
        f4809I = dv.m6428a(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
        f4810J = dv.m6427a(0, "gads:sdk_csi_write_to_file", Boolean.valueOf(false));
        f4811K = dv.m6427a(0, "gads:enable_content_fetching", Boolean.valueOf(true));
        f4812L = dv.m6425a(0, "gads:content_length_weight", 1);
        f4813M = dv.m6425a(0, "gads:content_age_weight", 1);
        f4814N = dv.m6425a(0, "gads:min_content_len", 11);
        f4815O = dv.m6425a(0, "gads:fingerprint_number", 10);
        f4816P = dv.m6425a(0, "gads:sleep_sec", 10);
        f4817Q = dv.m6427a(0, "gad:app_index_enabled", Boolean.valueOf(true));
        f4818R = dv.m6427a(0, "gads:app_index:without_content_info_present:enabled", Boolean.valueOf(true));
        f4819S = dv.m6426a(0, "gads:app_index:timeout_ms", 1000);
        f4820T = dv.m6424a(0, "gads:app_index:experiment_id");
        f4821U = dv.m6424a(0, "gads:kitkat_interstitial_workaround:experiment_id");
        f4822V = dv.m6427a(0, "gads:kitkat_interstitial_workaround:enabled", Boolean.valueOf(true));
        f4823W = dv.m6427a(0, "gads:interstitial_follow_url", Boolean.valueOf(true));
        f4824X = dv.m6427a(0, "gads:interstitial_follow_url:register_click", Boolean.valueOf(true));
        f4825Y = dv.m6424a(0, "gads:interstitial_follow_url:experiment_id");
        f4826Z = dv.m6427a(0, "gads:analytics_enabled", Boolean.valueOf(true));
        aa = dv.m6427a(0, "gads:ad_key_enabled", Boolean.valueOf(false));
        ab = dv.m6425a(0, "gads:webview_cache_version", 0);
        ac = dv.m6427a(1, "gads:webview_recycle:enabled", Boolean.valueOf(false));
        ad = dv.m6424a(1, "gads:webview_recycle:experiment_id");
        ae = dv.m6429b(0, "gads:pan:experiment_id");
        af = dv.m6428a(0, "gads:native:engine_url", "//googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
        ag = dv.m6427a(0, "gads:ad_manager_creator:enabled", Boolean.valueOf(true));
        ah = dv.m6427a(1, "gads:interstitial_ad_pool:enabled", Boolean.valueOf(false));
        ai = dv.m6427a(1, "gads:interstitial_ad_pool:enabled_for_rewarded", Boolean.valueOf(false));
        aj = dv.m6428a(1, "gads:interstitial_ad_pool:schema", "customTargeting");
        ak = dv.m6428a(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
        al = dv.m6425a(1, "gads:interstitial_ad_pool:max_pools", 3);
        am = dv.m6425a(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
        an = dv.m6425a(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
        ao = dv.m6428a(1, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
        ap = dv.m6428a(1, "gads:spherical_video:vertex_shader", StringUtils.EMPTY);
        aq = dv.m6428a(1, "gads:spherical_video:fragment_shader", StringUtils.EMPTY);
        ar = dv.m6424a(1, "gads:spherical_video:experiment_id");
        as = dv.m6427a(0, "gads:log:verbose_enabled", Boolean.valueOf(false));
        at = dv.m6427a(1, "gads:include_local_global_rectangles", Boolean.valueOf(false));
        au = dv.m6424a(1, "gads:include_local_global_rectangles:experiment_id");
        av = dv.m6427a(0, "gads:device_info_caching:enabled", Boolean.valueOf(true));
        aw = dv.m6426a(0, "gads:device_info_caching_expiry_ms:expiry", (long) Constants.LOCATION_UPDATE_TIME_INTERVAL_LOCAL_CONFIG_MINIMUM_MS);
        ax = dv.m6427a(0, "gads:gen204_signals:enabled", Boolean.valueOf(false));
        ay = dv.m6427a(0, "gads:webview:error_reporting_enabled", Boolean.valueOf(false));
        az = dv.m6427a(0, "gads:adid_reporting:enabled", Boolean.valueOf(false));
        aA = dv.m6427a(0, "gads:ad_settings_page_reporting:enabled", Boolean.valueOf(false));
        aB = dv.m6427a(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", Boolean.valueOf(false));
        aC = dv.m6427a(0, "gads:request_pkg:enabled", Boolean.valueOf(true));
        aD = dv.m6427a(0, "gads:gmsg:disable_back_button:enabled", Boolean.valueOf(false));
        aE = dv.m6427a(0, "gads:gmsg:video_meta:enabled", Boolean.valueOf(true));
        aF = dv.m6424a(0, "gads:gmsg:video_meta:experiment_id");
        aG = dv.m6426a(0, "gads:network:cache_prediction_duration_s", 300);
        aH = dv.m6427a(0, "gads:mediation:dynamite_first:admobadapter", Boolean.valueOf(true));
        aI = dv.m6427a(0, "gads:mediation:dynamite_first:adurladapter", Boolean.valueOf(true));
        aJ = dv.m6426a(0, "gads:ad_loader:timeout_ms", 60000);
        aK = dv.m6426a(0, "gads:rendering:timeout_ms", 60000);
        aL = dv.m6427a(0, "gads:adshield:enable_adshield_instrumentation", Boolean.valueOf(false));
        aM = dv.m6426a(1, "gads:gestures:task_timeout", 2000);
        aN = dv.m6424a(1, "gads:gestures:encrypt_size_limit:experiment_id");
        aO = dv.m6427a(1, "gads:gestures:encrypt_size_limit:enabled", Boolean.valueOf(true));
        aP = dv.m6424a(1, "gads:gestures:cpu:experiment_id");
        aQ = dv.m6427a(1, "gads:gestures:cpu_query:enabled", Boolean.valueOf(false));
        aR = dv.m6427a(1, "gads:gestures:cpu_click:enabled", Boolean.valueOf(false));
        aS = dv.m6424a(1, "gads:gestures:jbk:experiment_id");
        aT = dv.m6427a(1, "gads:gestures:jbk_query:enabled", Boolean.valueOf(false));
        aU = dv.m6427a(1, "gads:gestures:jbk_click:enabled", Boolean.valueOf(false));
        aV = dv.m6424a(1, "gads:gestures:stk:experiment_id");
        aW = dv.m6427a(1, "gads:gestures:stk:enabled", Boolean.valueOf(false));
        aX = dv.m6427a(0, "gass:enabled", Boolean.valueOf(false));
        aY = dv.m6427a(0, "gass:enable_int_signal", Boolean.valueOf(true));
        aZ = dv.m6427a(0, "gads:adid_notification:first_party_check:enabled", Boolean.valueOf(true));
        ba = dv.m6427a(0, "gads:edu_device_helper:enabled", Boolean.valueOf(true));
        bb = dv.m6427a(0, "gads:support_screen_shot", Boolean.valueOf(true));
        bc = dv.m6427a(0, "gads:use_get_drawing_cache_for_screenshot:enabled", Boolean.valueOf(true));
        bd = dv.m6424a(0, "gads:use_get_drawing_cache_for_screenshot:experiment_id");
        be = dv.m6426a(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12));
        bf = dv.m6427a(0, "gads:custom_render:ping_on_ad_rendered", Boolean.valueOf(false));
        bg = dv.m6427a(1, "gads:singleton_webview_native", Boolean.valueOf(false));
        bh = dv.m6424a(1, "gads:singleton_webview_native:experiment_id");
        bi = dv.m6427a(0, "gads:method_tracing:enabled", Boolean.valueOf(false));
        bj = dv.m6426a(0, "gads:method_tracing:duration_ms", 30000);
        bk = dv.m6425a(0, "gads:method_tracing:count", 5);
        bl = dv.m6425a(0, "gads:method_tracing:filesize", 134217728);
        bm = dv.m6427a(1, "gads:auto_location_for_coarse_permission", Boolean.valueOf(false));
        bn = dv.m6429b(1, "gads:auto_location_for_coarse_permission:experiment_id");
        bo = dv.m6426a(1, "gads:auto_location_timeout", 2000);
        bp = dv.m6429b(1, "gads:auto_location_timeout:experiment_id");
        bq = dv.m6426a(1, "gads:auto_location_interval", -1);
        br = dv.m6429b(1, "gads:auto_location_interval:experiment_id");
        bs = dv.m6427a(1, "gads:fetch_app_settings_using_cld:enabled", Boolean.valueOf(false));
        bt = dv.m6424a(1, "gads:fetch_app_settings_using_cld:enabled:experiment_id");
        bu = dv.m6426a(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000);
        bv = dv.m6424a(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms:experiment_id");
        bw = dv.m6424a(0, "gads:afs:csa:experiment_id");
        bx = dv.m6428a(0, "gads:afs:csa_webview_gmsg_ad_failed", "gmsg://noAdLoaded");
        by = dv.m6428a(0, "gads:afs:csa_webview_gmsg_script_load_failed", "gmsg://scriptLoadFailed");
        bz = dv.m6428a(0, "gads:afs:csa_webview_gmsg_ad_loaded", "gmsg://adResized");
        bA = dv.m6428a(0, "gads:afs:csa_webview_static_file_path", "/afs/ads/i/webview.html");
        bB = dv.m6428a(0, "gads:afs:csa_webview_custom_domain_param_key", "csa_customDomain");
        bC = dv.m6426a(0, "gads:afs:csa_webview_adshield_timeout_ms", 1000);
        bD = dv.m6427a(0, "gads:afs:csa_ad_manager_enabled", Boolean.valueOf(true));
        bE = dv.m6427a(0, "gads:safe_browsing:reporting:malicious:enabled", Boolean.valueOf(false));
        bF = dv.m6427a(0, "gads:safe_browsing:reporting:full:enabled", Boolean.valueOf(false));
        bG = dv.m6427a(0, "gads:safe_browsing:screenshot:enabled", Boolean.valueOf(false));
        bH = dv.m6428a(0, "gads:safe_browsing:reporting:url", "https://sb-ssl.google.com/safebrowsing/clientreport/malware");
        bI = dv.m6428a(0, "gads:safe_browsing:api_key", "AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
        bJ = dv.m6426a(0, "gads:safe_browsing:safety_net:delay_ms", 2000);
        bK = dv.m6424a(0, "gads:safe_browsing:experiment_id");
        bL = dv.m6427a(0, "gads:safe_browsing:debug", Boolean.valueOf(false));
        bM = dv.m6427a(0, "gads:webview_cookie:enabled", Boolean.valueOf(true));
    }

    public static List<String> m6443a() {
        return C1101o.m6049m().m6434a();
    }

    public static void m6444a(Context context) {
        mt.m7191a(new 1(context));
    }

    public static List<String> m6445b() {
        return C1101o.m6049m().m6436b();
    }
}
