package com.etsy.android;

import com.appboy.ui.C0401R;

/* renamed from: com.etsy.android.d */
public final class R {
    public static final int[] ActionBar;
    public static final int[] ActionBarLayout;
    public static final int ActionBarLayout_android_layout_gravity = 0;
    public static final int ActionBar_background = 10;
    public static final int ActionBar_backgroundSplit = 12;
    public static final int ActionBar_backgroundStacked = 11;
    public static final int ActionBar_contentInsetEnd = 21;
    public static final int ActionBar_contentInsetLeft = 22;
    public static final int ActionBar_contentInsetRight = 23;
    public static final int ActionBar_contentInsetStart = 20;
    public static final int ActionBar_customNavigationLayout = 13;
    public static final int ActionBar_displayOptions = 3;
    public static final int ActionBar_divider = 9;
    public static final int ActionBar_elevation = 24;
    public static final int ActionBar_height = 0;
    public static final int ActionBar_hideOnContentScroll = 19;
    public static final int ActionBar_homeAsUpIndicator = 26;
    public static final int ActionBar_homeLayout = 14;
    public static final int ActionBar_icon = 7;
    public static final int ActionBar_indeterminateProgressStyle = 16;
    public static final int ActionBar_itemPadding = 18;
    public static final int ActionBar_logo = 8;
    public static final int ActionBar_navigationMode = 2;
    public static final int ActionBar_popupTheme = 25;
    public static final int ActionBar_progressBarPadding = 17;
    public static final int ActionBar_progressBarStyle = 15;
    public static final int ActionBar_subtitle = 4;
    public static final int ActionBar_subtitleTextStyle = 6;
    public static final int ActionBar_title = 1;
    public static final int ActionBar_titleTextStyle = 5;
    public static final int[] ActionMenuItemView;
    public static final int ActionMenuItemView_android_minWidth = 0;
    public static final int[] ActionMenuView;
    public static final int[] ActionMode;
    public static final int ActionMode_background = 3;
    public static final int ActionMode_backgroundSplit = 4;
    public static final int ActionMode_closeItemLayout = 5;
    public static final int ActionMode_height = 0;
    public static final int ActionMode_subtitleTextStyle = 2;
    public static final int ActionMode_titleTextStyle = 1;
    public static final int[] ActivityChooserView;
    public static final int ActivityChooserView_expandActivityOverflowButtonDrawable = 1;
    public static final int ActivityChooserView_initialActivityCount = 0;
    public static final int[] AdsAttrs;
    public static final int AdsAttrs_adSize = 0;
    public static final int AdsAttrs_adSizes = 1;
    public static final int AdsAttrs_adUnitId = 2;
    public static final int[] AlertDialog;
    public static final int AlertDialog_android_layout = 0;
    public static final int AlertDialog_buttonPanelSideLayout = 1;
    public static final int AlertDialog_listItemLayout = 5;
    public static final int AlertDialog_listLayout = 2;
    public static final int AlertDialog_multiChoiceItemLayout = 3;
    public static final int AlertDialog_singleChoiceItemLayout = 4;
    public static final int[] AppBarLayout;
    public static final int[] AppBarLayout_LayoutParams;
    public static final int AppBarLayout_LayoutParams_layout_scrollFlags = 0;
    public static final int AppBarLayout_LayoutParams_layout_scrollInterpolator = 1;
    public static final int AppBarLayout_android_background = 0;
    public static final int AppBarLayout_elevation = 1;
    public static final int AppBarLayout_expanded = 2;
    public static final int[] AppCompatImageView;
    public static final int AppCompatImageView_android_src = 0;
    public static final int AppCompatImageView_srcCompat = 1;
    public static final int[] AppCompatTextView;
    public static final int AppCompatTextView_android_textAppearance = 0;
    public static final int AppCompatTextView_textAllCaps = 1;
    public static final int[] AppCompatTheme;
    public static final int AppCompatTheme_actionBarDivider = 23;
    public static final int AppCompatTheme_actionBarItemBackground = 24;
    public static final int AppCompatTheme_actionBarPopupTheme = 17;
    public static final int AppCompatTheme_actionBarSize = 22;
    public static final int AppCompatTheme_actionBarSplitStyle = 19;
    public static final int AppCompatTheme_actionBarStyle = 18;
    public static final int AppCompatTheme_actionBarTabBarStyle = 13;
    public static final int AppCompatTheme_actionBarTabStyle = 12;
    public static final int AppCompatTheme_actionBarTabTextStyle = 14;
    public static final int AppCompatTheme_actionBarTheme = 20;
    public static final int AppCompatTheme_actionBarWidgetTheme = 21;
    public static final int AppCompatTheme_actionButtonStyle = 49;
    public static final int AppCompatTheme_actionDropDownStyle = 45;
    public static final int AppCompatTheme_actionMenuTextAppearance = 25;
    public static final int AppCompatTheme_actionMenuTextColor = 26;
    public static final int AppCompatTheme_actionModeBackground = 29;
    public static final int AppCompatTheme_actionModeCloseButtonStyle = 28;
    public static final int AppCompatTheme_actionModeCloseDrawable = 31;
    public static final int AppCompatTheme_actionModeCopyDrawable = 33;
    public static final int AppCompatTheme_actionModeCutDrawable = 32;
    public static final int AppCompatTheme_actionModeFindDrawable = 37;
    public static final int AppCompatTheme_actionModePasteDrawable = 34;
    public static final int AppCompatTheme_actionModePopupWindowStyle = 39;
    public static final int AppCompatTheme_actionModeSelectAllDrawable = 35;
    public static final int AppCompatTheme_actionModeShareDrawable = 36;
    public static final int AppCompatTheme_actionModeSplitBackground = 30;
    public static final int AppCompatTheme_actionModeStyle = 27;
    public static final int AppCompatTheme_actionModeWebSearchDrawable = 38;
    public static final int AppCompatTheme_actionOverflowButtonStyle = 15;
    public static final int AppCompatTheme_actionOverflowMenuStyle = 16;
    public static final int AppCompatTheme_activityChooserViewStyle = 57;
    public static final int AppCompatTheme_alertDialogButtonGroupStyle = 92;
    public static final int AppCompatTheme_alertDialogCenterButtons = 93;
    public static final int AppCompatTheme_alertDialogStyle = 91;
    public static final int AppCompatTheme_alertDialogTheme = 94;
    public static final int AppCompatTheme_android_windowAnimationStyle = 1;
    public static final int AppCompatTheme_android_windowIsFloating = 0;
    public static final int AppCompatTheme_autoCompleteTextViewStyle = 99;
    public static final int AppCompatTheme_borderlessButtonStyle = 54;
    public static final int AppCompatTheme_buttonBarButtonStyle = 51;
    public static final int AppCompatTheme_buttonBarNegativeButtonStyle = 97;
    public static final int AppCompatTheme_buttonBarNeutralButtonStyle = 98;
    public static final int AppCompatTheme_buttonBarPositiveButtonStyle = 96;
    public static final int AppCompatTheme_buttonBarStyle = 50;
    public static final int AppCompatTheme_buttonStyle = 100;
    public static final int AppCompatTheme_buttonStyleSmall = 101;
    public static final int AppCompatTheme_checkboxStyle = 102;
    public static final int AppCompatTheme_checkedTextViewStyle = 103;
    public static final int AppCompatTheme_colorAccent = 84;
    public static final int AppCompatTheme_colorButtonNormal = 88;
    public static final int AppCompatTheme_colorControlActivated = 86;
    public static final int AppCompatTheme_colorControlHighlight = 87;
    public static final int AppCompatTheme_colorControlNormal = 85;
    public static final int AppCompatTheme_colorPrimary = 82;
    public static final int AppCompatTheme_colorPrimaryDark = 83;
    public static final int AppCompatTheme_colorSwitchThumbNormal = 89;
    public static final int AppCompatTheme_controlBackground = 90;
    public static final int AppCompatTheme_dialogPreferredPadding = 43;
    public static final int AppCompatTheme_dialogTheme = 42;
    public static final int AppCompatTheme_dividerHorizontal = 56;
    public static final int AppCompatTheme_dividerVertical = 55;
    public static final int AppCompatTheme_dropDownListViewStyle = 74;
    public static final int AppCompatTheme_dropdownListPreferredItemHeight = 46;
    public static final int AppCompatTheme_editTextBackground = 63;
    public static final int AppCompatTheme_editTextColor = 62;
    public static final int AppCompatTheme_editTextStyle = 104;
    public static final int AppCompatTheme_homeAsUpIndicator = 48;
    public static final int AppCompatTheme_imageButtonStyle = 64;
    public static final int AppCompatTheme_listChoiceBackgroundIndicator = 81;
    public static final int AppCompatTheme_listDividerAlertDialog = 44;
    public static final int AppCompatTheme_listPopupWindowStyle = 75;
    public static final int AppCompatTheme_listPreferredItemHeight = 69;
    public static final int AppCompatTheme_listPreferredItemHeightLarge = 71;
    public static final int AppCompatTheme_listPreferredItemHeightSmall = 70;
    public static final int AppCompatTheme_listPreferredItemPaddingLeft = 72;
    public static final int AppCompatTheme_listPreferredItemPaddingRight = 73;
    public static final int AppCompatTheme_panelBackground = 78;
    public static final int AppCompatTheme_panelMenuListTheme = 80;
    public static final int AppCompatTheme_panelMenuListWidth = 79;
    public static final int AppCompatTheme_popupMenuStyle = 60;
    public static final int AppCompatTheme_popupWindowStyle = 61;
    public static final int AppCompatTheme_radioButtonStyle = 105;
    public static final int AppCompatTheme_ratingBarStyle = 106;
    public static final int AppCompatTheme_ratingBarStyleIndicator = 107;
    public static final int AppCompatTheme_ratingBarStyleSmall = 108;
    public static final int AppCompatTheme_searchViewStyle = 68;
    public static final int AppCompatTheme_seekBarStyle = 109;
    public static final int AppCompatTheme_selectableItemBackground = 52;
    public static final int AppCompatTheme_selectableItemBackgroundBorderless = 53;
    public static final int AppCompatTheme_spinnerDropDownItemStyle = 47;
    public static final int AppCompatTheme_spinnerStyle = 110;
    public static final int AppCompatTheme_switchStyle = 111;
    public static final int AppCompatTheme_textAppearanceLargePopupMenu = 40;
    public static final int AppCompatTheme_textAppearanceListItem = 76;
    public static final int AppCompatTheme_textAppearanceListItemSmall = 77;
    public static final int AppCompatTheme_textAppearanceSearchResultSubtitle = 66;
    public static final int AppCompatTheme_textAppearanceSearchResultTitle = 65;
    public static final int AppCompatTheme_textAppearanceSmallPopupMenu = 41;
    public static final int AppCompatTheme_textColorAlertDialogListItem = 95;
    public static final int AppCompatTheme_textColorSearchUrl = 67;
    public static final int AppCompatTheme_toolbarNavigationButtonStyle = 59;
    public static final int AppCompatTheme_toolbarStyle = 58;
    public static final int AppCompatTheme_windowActionBar = 2;
    public static final int AppCompatTheme_windowActionBarOverlay = 4;
    public static final int AppCompatTheme_windowActionModeOverlay = 5;
    public static final int AppCompatTheme_windowFixedHeightMajor = 9;
    public static final int AppCompatTheme_windowFixedHeightMinor = 7;
    public static final int AppCompatTheme_windowFixedWidthMajor = 6;
    public static final int AppCompatTheme_windowFixedWidthMinor = 8;
    public static final int AppCompatTheme_windowMinWidthMajor = 10;
    public static final int AppCompatTheme_windowMinWidthMinor = 11;
    public static final int AppCompatTheme_windowNoTitle = 3;
    public static final int[] AppDataSearch;
    public static final int[] BaseSplitView;
    public static final int BaseSplitView_empty_layout = 0;
    public static final int BaseSplitView_no_internet_layout = 1;
    public static final int BaseSplitView_side_panel_fraction = 2;
    public static final int[] BottomSheetBehavior_Params;
    public static final int BottomSheetBehavior_Params_behavior_hideable = 1;
    public static final int BottomSheetBehavior_Params_behavior_peekHeight = 0;
    public static final int[] ButtonBarLayout;
    public static final int ButtonBarLayout_allowStacking = 0;
    public static final int[] CardTabView;
    public static final int CardTabView_tabWidgetBackground = 0;
    public static final int[] CardView;
    public static final int CardView_android_minHeight = 1;
    public static final int CardView_android_minWidth = 0;
    public static final int CardView_cardBackgroundColor = 2;
    public static final int CardView_cardCornerRadius = 3;
    public static final int CardView_cardElevation = 4;
    public static final int CardView_cardMaxElevation = 5;
    public static final int CardView_cardPreventCornerOverlap = 7;
    public static final int CardView_cardUseCompatPadding = 6;
    public static final int CardView_contentPadding = 8;
    public static final int CardView_contentPaddingBottom = 12;
    public static final int CardView_contentPaddingLeft = 9;
    public static final int CardView_contentPaddingRight = 10;
    public static final int CardView_contentPaddingTop = 11;
    public static final int[] CharacterCounterView;
    public static final int CharacterCounterView_format = 1;
    public static final int CharacterCounterView_maxChars = 0;
    public static final int[] CirclePageIndicator;
    public static final int CirclePageIndicator_android_background = 1;
    public static final int CirclePageIndicator_android_orientation = 0;
    public static final int CirclePageIndicator_centered = 2;
    public static final int CirclePageIndicator_fillColor = 4;
    public static final int CirclePageIndicator_pageColor = 5;
    public static final int CirclePageIndicator_radius = 6;
    public static final int CirclePageIndicator_snap = 7;
    public static final int CirclePageIndicator_strokeColor = 8;
    public static final int CirclePageIndicator_strokeWidth = 3;
    public static final int[] CollapsingAppBarLayout_LayoutParams;
    public static final int CollapsingAppBarLayout_LayoutParams_layout_collapseMode = 0;
    public static final int f1112xad49a364 = 1;
    public static final int[] CollapsingToolbarLayout;
    public static final int CollapsingToolbarLayout_collapsedTitleGravity = 11;
    public static final int CollapsingToolbarLayout_collapsedTitleTextAppearance = 7;
    public static final int CollapsingToolbarLayout_contentScrim = 8;
    public static final int CollapsingToolbarLayout_expandedTitleGravity = 12;
    public static final int CollapsingToolbarLayout_expandedTitleMargin = 1;
    public static final int CollapsingToolbarLayout_expandedTitleMarginBottom = 5;
    public static final int CollapsingToolbarLayout_expandedTitleMarginEnd = 4;
    public static final int CollapsingToolbarLayout_expandedTitleMarginStart = 2;
    public static final int CollapsingToolbarLayout_expandedTitleMarginTop = 3;
    public static final int CollapsingToolbarLayout_expandedTitleTextAppearance = 6;
    public static final int CollapsingToolbarLayout_statusBarScrim = 9;
    public static final int CollapsingToolbarLayout_title = 0;
    public static final int CollapsingToolbarLayout_titleEnabled = 13;
    public static final int CollapsingToolbarLayout_toolbarId = 10;
    public static final int[] CompoundButton;
    public static final int CompoundButton_android_button = 0;
    public static final int CompoundButton_buttonTint = 1;
    public static final int CompoundButton_buttonTintMode = 2;
    public static final int[] CoordinatorLayout;
    public static final int[] CoordinatorLayout_LayoutParams;
    public static final int CoordinatorLayout_LayoutParams_android_layout_gravity = 0;
    public static final int CoordinatorLayout_LayoutParams_layout_anchor = 2;
    public static final int CoordinatorLayout_LayoutParams_layout_anchorGravity = 4;
    public static final int CoordinatorLayout_LayoutParams_layout_behavior = 1;
    public static final int CoordinatorLayout_LayoutParams_layout_keyline = 3;
    public static final int CoordinatorLayout_keylines = 0;
    public static final int CoordinatorLayout_statusBarBackground = 1;
    public static final int[] Corpus;
    public static final int Corpus_contentProviderUri = 2;
    public static final int Corpus_corpusId = 0;
    public static final int Corpus_corpusVersion = 1;
    public static final int Corpus_perAccountTemplate = 6;
    public static final int Corpus_schemaOrgType = 4;
    public static final int Corpus_semanticallySearchable = 5;
    public static final int Corpus_trimmable = 3;
    public static final int[] CustomWalletTheme;
    public static final int CustomWalletTheme_windowTransitionStyle = 0;
    public static final int[] DesignTheme;
    public static final int DesignTheme_bottomSheetDialogTheme = 0;
    public static final int DesignTheme_bottomSheetStyle = 1;
    public static final int DesignTheme_textColorError = 2;
    public static final int[] DiagonalStrikeImageView;
    public static final int DiagonalStrikeImageView_diagonalLineColor = 0;
    public static final int DiagonalStrikeImageView_diagonalLineWidth = 1;
    public static final int[] DrawerArrowToggle;
    public static final int DrawerArrowToggle_arrowHeadLength = 4;
    public static final int DrawerArrowToggle_arrowShaftLength = 5;
    public static final int DrawerArrowToggle_barLength = 6;
    public static final int DrawerArrowToggle_color = 0;
    public static final int DrawerArrowToggle_drawableSize = 2;
    public static final int DrawerArrowToggle_gapBetweenBars = 3;
    public static final int DrawerArrowToggle_spinBars = 1;
    public static final int DrawerArrowToggle_thickness = 7;
    public static final int[] EtsyTabView;
    public static final int EtsyTabView_tabLayout = 0;
    public static final int[] FeatureParam;
    public static final int FeatureParam_paramName = 0;
    public static final int FeatureParam_paramValue = 1;
    public static final int[] FindsCardView;
    public static final int FindsCardView_aspectRatio = 0;
    public static final int[] FloatingActionButton;
    public static final int FloatingActionButton_backgroundTint = 6;
    public static final int FloatingActionButton_backgroundTintMode = 7;
    public static final int FloatingActionButton_borderWidth = 4;
    public static final int FloatingActionButton_elevation = 0;
    public static final int FloatingActionButton_fabSize = 2;
    public static final int FloatingActionButton_pressedTranslationZ = 3;
    public static final int FloatingActionButton_rippleColor = 1;
    public static final int FloatingActionButton_useCompatPadding = 5;
    public static final int[] FlowLayout;
    public static final int[] FlowLayout_LayoutParams;
    public static final int FlowLayout_LayoutParams_layout_breakLine = 0;
    public static final int FlowLayout_horizontalSpacing = 0;
    public static final int FlowLayout_verticalSpacing = 1;
    public static final int[] ForegroundImageView;
    public static final int ForegroundImageView_foreground = 0;
    public static final int[] ForegroundLinearLayout;
    public static final int ForegroundLinearLayout_android_foreground = 0;
    public static final int ForegroundLinearLayout_android_foregroundGravity = 1;
    public static final int ForegroundLinearLayout_foregroundInsidePadding = 2;
    public static final int[] FullImageView;
    public static final int FullImageView_imageAspect = 0;
    public static final int[] GlobalSearch;
    public static final int[] GlobalSearchCorpus;
    public static final int GlobalSearchCorpus_allowShortcuts = 0;
    public static final int[] GlobalSearchSection;
    public static final int GlobalSearchSection_sectionContent = 1;
    public static final int GlobalSearchSection_sectionType = 0;
    public static final int GlobalSearch_defaultIntentAction = 3;
    public static final int GlobalSearch_defaultIntentActivity = 5;
    public static final int GlobalSearch_defaultIntentData = 4;
    public static final int GlobalSearch_searchEnabled = 0;
    public static final int GlobalSearch_searchLabel = 1;
    public static final int GlobalSearch_settingsDescription = 2;
    public static final int[] GridLayout;
    public static final int[] GridLayout_Layout;
    public static final int GridLayout_Layout_android_layout_height = 1;
    public static final int GridLayout_Layout_android_layout_margin = 2;
    public static final int GridLayout_Layout_android_layout_marginBottom = 6;
    public static final int GridLayout_Layout_android_layout_marginLeft = 3;
    public static final int GridLayout_Layout_android_layout_marginRight = 5;
    public static final int GridLayout_Layout_android_layout_marginTop = 4;
    public static final int GridLayout_Layout_android_layout_width = 0;
    public static final int GridLayout_Layout_layout_column = 10;
    public static final int GridLayout_Layout_layout_columnSpan = 11;
    public static final int GridLayout_Layout_layout_columnWeight = 12;
    public static final int GridLayout_Layout_layout_gravity = 13;
    public static final int GridLayout_Layout_layout_row = 7;
    public static final int GridLayout_Layout_layout_rowSpan = 8;
    public static final int GridLayout_Layout_layout_rowWeight = 9;
    public static final int GridLayout_alignmentMode = 4;
    public static final int GridLayout_columnCount = 2;
    public static final int GridLayout_columnOrderPreserved = 6;
    public static final int GridLayout_orientation = 0;
    public static final int GridLayout_rowCount = 1;
    public static final int GridLayout_rowOrderPreserved = 5;
    public static final int GridLayout_useDefaultMargins = 3;
    public static final int[] IMECorpus;
    public static final int IMECorpus_inputEnabled = 0;
    public static final int IMECorpus_sourceClass = 1;
    public static final int IMECorpus_toAddressesSection = 5;
    public static final int IMECorpus_userInputSection = 3;
    public static final int IMECorpus_userInputTag = 2;
    public static final int IMECorpus_userInputValue = 4;
    public static final int[] IconView;
    public static final int IconView_alpha = 3;
    public static final int IconView_gravity = 1;
    public static final int IconView_hasSelector = 4;
    public static final int IconView_iconChar = 0;
    public static final int IconView_iconColor = 2;
    public static final int[] ImageAttachmentLayout;
    public static final int ImageAttachmentLayout_attachmentPadding = 0;
    public static final int[] ImageViewWithAspectRatio;
    public static final int ImageViewWithAspectRatio_doMaintainAspect = 1;
    public static final int ImageViewWithAspectRatio_heightRatio = 0;
    public static final int[] LazyNativeAssetImageView;
    public static final int LazyNativeAssetImageView_img = 0;
    public static final int[] LinePageIndicator;
    public static final int LinePageIndicator_android_background = 0;
    public static final int LinePageIndicator_centered = 1;
    public static final int LinePageIndicator_gapWidth = 6;
    public static final int LinePageIndicator_lineWidth = 5;
    public static final int LinePageIndicator_selectedColor = 2;
    public static final int LinePageIndicator_strokeWidth = 3;
    public static final int LinePageIndicator_unselectedColor = 4;
    public static final int[] LinearLayoutCompat;
    public static final int[] LinearLayoutCompat_Layout;
    public static final int LinearLayoutCompat_Layout_android_layout_gravity = 0;
    public static final int LinearLayoutCompat_Layout_android_layout_height = 2;
    public static final int LinearLayoutCompat_Layout_android_layout_weight = 3;
    public static final int LinearLayoutCompat_Layout_android_layout_width = 1;
    public static final int LinearLayoutCompat_android_baselineAligned = 2;
    public static final int LinearLayoutCompat_android_baselineAlignedChildIndex = 3;
    public static final int LinearLayoutCompat_android_gravity = 0;
    public static final int LinearLayoutCompat_android_orientation = 1;
    public static final int LinearLayoutCompat_android_weightSum = 4;
    public static final int LinearLayoutCompat_divider = 5;
    public static final int LinearLayoutCompat_dividerPadding = 8;
    public static final int LinearLayoutCompat_measureWithLargestChild = 6;
    public static final int LinearLayoutCompat_showDividers = 7;
    public static final int[] ListPopupWindow;
    public static final int ListPopupWindow_android_dropDownHorizontalOffset = 0;
    public static final int ListPopupWindow_android_dropDownVerticalOffset = 1;
    public static final int[] LoadingImageView;
    public static final int LoadingImageView_circleCrop = 2;
    public static final int LoadingImageView_imageAspectRatio = 1;
    public static final int LoadingImageView_imageAspectRatioAdjust = 0;
    public static final int[] MachineTranslationOneClickView;
    public static final int MachineTranslationOneClickView_activeButtonColor = 2;
    public static final int MachineTranslationOneClickView_disclaimerText = 3;
    public static final int MachineTranslationOneClickView_inactiveButtonColor = 1;
    public static final int MachineTranslationOneClickView_textSize = 0;
    public static final int[] MapAttrs;
    public static final int MapAttrs_ambientEnabled = 16;
    public static final int MapAttrs_cameraBearing = 1;
    public static final int MapAttrs_cameraTargetLat = 2;
    public static final int MapAttrs_cameraTargetLng = 3;
    public static final int MapAttrs_cameraTilt = 4;
    public static final int MapAttrs_cameraZoom = 5;
    public static final int MapAttrs_liteMode = 6;
    public static final int MapAttrs_mapType = 0;
    public static final int MapAttrs_uiCompass = 7;
    public static final int MapAttrs_uiMapToolbar = 15;
    public static final int MapAttrs_uiRotateGestures = 8;
    public static final int MapAttrs_uiScrollGestures = 9;
    public static final int MapAttrs_uiTiltGestures = 10;
    public static final int MapAttrs_uiZoomControls = 11;
    public static final int MapAttrs_uiZoomGestures = 12;
    public static final int MapAttrs_useViewLifecycle = 13;
    public static final int MapAttrs_zOrderOnTop = 14;
    public static final int[] MaxWidthLayout;
    public static final int MaxWidthLayout_maxWidth = 0;
    public static final int[] MenuGroup;
    public static final int MenuGroup_android_checkableBehavior = 5;
    public static final int MenuGroup_android_enabled = 0;
    public static final int MenuGroup_android_id = 1;
    public static final int MenuGroup_android_menuCategory = 3;
    public static final int MenuGroup_android_orderInCategory = 4;
    public static final int MenuGroup_android_visible = 2;
    public static final int[] MenuItem;
    public static final int MenuItem_actionLayout = 14;
    public static final int MenuItem_actionProviderClass = 16;
    public static final int MenuItem_actionViewClass = 15;
    public static final int MenuItem_android_alphabeticShortcut = 9;
    public static final int MenuItem_android_checkable = 11;
    public static final int MenuItem_android_checked = 3;
    public static final int MenuItem_android_enabled = 1;
    public static final int MenuItem_android_icon = 0;
    public static final int MenuItem_android_id = 2;
    public static final int MenuItem_android_menuCategory = 5;
    public static final int MenuItem_android_numericShortcut = 10;
    public static final int MenuItem_android_onClick = 12;
    public static final int MenuItem_android_orderInCategory = 6;
    public static final int MenuItem_android_title = 7;
    public static final int MenuItem_android_titleCondensed = 8;
    public static final int MenuItem_android_visible = 4;
    public static final int MenuItem_showAsAction = 13;
    public static final int[] MenuView;
    public static final int MenuView_android_headerBackground = 4;
    public static final int MenuView_android_horizontalDivider = 2;
    public static final int MenuView_android_itemBackground = 5;
    public static final int MenuView_android_itemIconDisabledAlpha = 6;
    public static final int MenuView_android_itemTextAppearance = 1;
    public static final int MenuView_android_verticalDivider = 3;
    public static final int MenuView_android_windowAnimationStyle = 0;
    public static final int MenuView_preserveIconSpacing = 7;
    public static final int[] NavigationView;
    public static final int NavigationView_android_background = 0;
    public static final int NavigationView_android_fitsSystemWindows = 1;
    public static final int NavigationView_android_maxWidth = 2;
    public static final int NavigationView_elevation = 3;
    public static final int NavigationView_headerLayout = 9;
    public static final int NavigationView_itemBackground = 7;
    public static final int NavigationView_itemIconTint = 5;
    public static final int NavigationView_itemTextAppearance = 8;
    public static final int NavigationView_itemTextColor = 6;
    public static final int NavigationView_menu = 4;
    public static final int[] PopupWindow;
    public static final int[] PopupWindowBackgroundState;
    public static final int PopupWindowBackgroundState_state_above_anchor = 0;
    public static final int PopupWindow_android_popupBackground = 0;
    public static final int PopupWindow_overlapAnchor = 1;
    public static final int[] ProgressButton;
    public static final int ProgressButton_activityIndicatorDrawable = 3;
    public static final int ProgressButton_drawableLeft = 1;
    public static final int ProgressButton_text = 0;
    public static final int ProgressButton_textStyleResource = 2;
    public static final int[] RangedProgressBar;
    public static final int RangedProgressBar_waypointLabels = 1;
    public static final int RangedProgressBar_waypointLevels = 2;
    public static final int RangedProgressBar_waypointValues = 0;
    public static final int[] RatingStarBar;
    public static final int RatingStarBar_starSize = 0;
    public static final int[] ReadState;
    public static final int ReadState_state_read = 0;
    public static final int[] RecyclerView;
    public static final int RecyclerView_android_orientation = 0;
    public static final int RecyclerView_layoutManager = 1;
    public static final int RecyclerView_reverseLayout = 3;
    public static final int RecyclerView_spanCount = 2;
    public static final int RecyclerView_stackFromEnd = 4;
    public static final int[] RoundStrokedCheckBox;
    public static final int RoundStrokedCheckBox_selectedBackgroundColor = 2;
    public static final int RoundStrokedCheckBox_selectedDrawableColor = 3;
    public static final int RoundStrokedCheckBox_selectedDrawableInset = 4;
    public static final int RoundStrokedCheckBox_unselectedStrokeColor = 1;
    public static final int RoundStrokedCheckBox_unselectedStrokeWidth = 0;
    public static final int[] ScrimInsetsFrameLayout;
    public static final int ScrimInsetsFrameLayout_insetForeground = 0;
    public static final int[] ScrollingViewBehavior_Params;
    public static final int ScrollingViewBehavior_Params_behavior_overlapTop = 0;
    public static final int[] SearchView;
    public static final int SearchView_android_focusable = 0;
    public static final int SearchView_android_imeOptions = 3;
    public static final int SearchView_android_inputType = 2;
    public static final int SearchView_android_maxWidth = 1;
    public static final int SearchView_closeIcon = 8;
    public static final int SearchView_commitIcon = 13;
    public static final int SearchView_defaultQueryHint = 7;
    public static final int SearchView_goIcon = 9;
    public static final int SearchView_iconifiedByDefault = 5;
    public static final int SearchView_layout = 4;
    public static final int SearchView_queryBackground = 15;
    public static final int SearchView_queryHint = 6;
    public static final int SearchView_searchHintIcon = 11;
    public static final int SearchView_searchIcon = 10;
    public static final int SearchView_submitBackground = 16;
    public static final int SearchView_suggestionRowLayout = 14;
    public static final int SearchView_voiceIcon = 12;
    public static final int[] Section;
    public static final int[] SectionFeature;
    public static final int SectionFeature_featureType = 0;
    public static final int Section_indexPrefixes = 4;
    public static final int Section_noIndex = 2;
    public static final int Section_schemaOrgProperty = 6;
    public static final int Section_sectionFormat = 1;
    public static final int Section_sectionId = 0;
    public static final int Section_sectionWeight = 3;
    public static final int Section_subsectionSeparator = 5;
    public static final int[] SignInButton;
    public static final int SignInButton_buttonSize = 0;
    public static final int SignInButton_colorScheme = 1;
    public static final int SignInButton_scopeUris = 2;
    public static final int[] SnackbarLayout;
    public static final int SnackbarLayout_android_maxWidth = 0;
    public static final int SnackbarLayout_elevation = 1;
    public static final int SnackbarLayout_maxActionInlineWidth = 2;
    public static final int[] Spinner;
    public static final int Spinner_android_dropDownWidth = 3;
    public static final int Spinner_android_entries = 0;
    public static final int Spinner_android_popupBackground = 1;
    public static final int Spinner_android_prompt = 2;
    public static final int Spinner_popupTheme = 4;
    public static final int[] StructuredShopPoliciesView;
    public static final int StructuredShopPoliciesView_editMode = 0;
    public static final int StructuredShopPoliciesView_structuredPoliciesSubheadStyle = 1;
    public static final int StructuredShopPoliciesView_structuredPoliciesTextLightStyle = 3;
    public static final int StructuredShopPoliciesView_structuredPoliciesTextStyle = 2;
    public static final int[] SwitchCompat;
    public static final int SwitchCompat_android_textOff = 1;
    public static final int SwitchCompat_android_textOn = 0;
    public static final int SwitchCompat_android_thumb = 2;
    public static final int SwitchCompat_showText = 9;
    public static final int SwitchCompat_splitTrack = 8;
    public static final int SwitchCompat_switchMinWidth = 6;
    public static final int SwitchCompat_switchPadding = 7;
    public static final int SwitchCompat_switchTextAppearance = 5;
    public static final int SwitchCompat_thumbTextPadding = 4;
    public static final int SwitchCompat_track = 3;
    public static final int[] SwitchToggle;
    public static final int SwitchToggle_android_textOff = 1;
    public static final int SwitchToggle_android_textOn = 0;
    public static final int[] TabItem;
    public static final int TabItem_android_icon = 0;
    public static final int TabItem_android_layout = 1;
    public static final int TabItem_android_text = 2;
    public static final int[] TabLayout;
    public static final int TabLayout_tabBackground = 3;
    public static final int TabLayout_tabContentStart = 2;
    public static final int TabLayout_tabGravity = 5;
    public static final int TabLayout_tabIndicatorColor = 0;
    public static final int TabLayout_tabIndicatorHeight = 1;
    public static final int TabLayout_tabMaxWidth = 7;
    public static final int TabLayout_tabMinWidth = 6;
    public static final int TabLayout_tabMode = 4;
    public static final int TabLayout_tabPadding = 15;
    public static final int TabLayout_tabPaddingBottom = 14;
    public static final int TabLayout_tabPaddingEnd = 13;
    public static final int TabLayout_tabPaddingStart = 11;
    public static final int TabLayout_tabPaddingTop = 12;
    public static final int TabLayout_tabSelectedTextColor = 10;
    public static final int TabLayout_tabTextAppearance = 8;
    public static final int TabLayout_tabTextColor = 9;
    public static final int[] TaggableImageView;
    public static final int TaggableImageView_editable = 0;
    public static final int[] TextAppearance;
    public static final int TextAppearance_android_shadowColor = 4;
    public static final int TextAppearance_android_shadowDx = 5;
    public static final int TextAppearance_android_shadowDy = 6;
    public static final int TextAppearance_android_shadowRadius = 7;
    public static final int TextAppearance_android_textColor = 3;
    public static final int TextAppearance_android_textSize = 0;
    public static final int TextAppearance_android_textStyle = 2;
    public static final int TextAppearance_android_typeface = 1;
    public static final int TextAppearance_textAllCaps = 8;
    public static final int[] TextInputLayout;
    public static final int TextInputLayout_android_hint = 1;
    public static final int TextInputLayout_android_textColorHint = 0;
    public static final int TextInputLayout_counterEnabled = 6;
    public static final int TextInputLayout_counterMaxLength = 7;
    public static final int TextInputLayout_counterOverflowTextAppearance = 9;
    public static final int TextInputLayout_counterTextAppearance = 8;
    public static final int TextInputLayout_errorEnabled = 4;
    public static final int TextInputLayout_errorTextAppearance = 5;
    public static final int TextInputLayout_hintAnimationEnabled = 10;
    public static final int TextInputLayout_hintEnabled = 3;
    public static final int TextInputLayout_hintTextAppearance = 2;
    public static final int[] TitlePageIndicator;
    public static final int TitlePageIndicator_android_background = 2;
    public static final int TitlePageIndicator_android_textColor = 1;
    public static final int TitlePageIndicator_android_textSize = 0;
    public static final int TitlePageIndicator_clipPadding = 4;
    public static final int TitlePageIndicator_footerColor = 5;
    public static final int TitlePageIndicator_footerIndicatorHeight = 8;
    public static final int TitlePageIndicator_footerIndicatorStyle = 7;
    public static final int TitlePageIndicator_footerIndicatorUnderlinePadding = 9;
    public static final int TitlePageIndicator_footerLineHeight = 6;
    public static final int TitlePageIndicator_footerPadding = 10;
    public static final int TitlePageIndicator_linePosition = 11;
    public static final int TitlePageIndicator_selectedBold = 12;
    public static final int TitlePageIndicator_selectedColor = 3;
    public static final int TitlePageIndicator_titlePadding = 13;
    public static final int TitlePageIndicator_topPadding = 14;
    public static final int[] Toolbar;
    public static final int Toolbar_android_gravity = 0;
    public static final int Toolbar_android_minHeight = 1;
    public static final int Toolbar_collapseContentDescription = 19;
    public static final int Toolbar_collapseIcon = 18;
    public static final int Toolbar_contentInsetEnd = 6;
    public static final int Toolbar_contentInsetLeft = 7;
    public static final int Toolbar_contentInsetRight = 8;
    public static final int Toolbar_contentInsetStart = 5;
    public static final int Toolbar_logo = 4;
    public static final int Toolbar_logoDescription = 22;
    public static final int Toolbar_maxButtonHeight = 17;
    public static final int Toolbar_navigationContentDescription = 21;
    public static final int Toolbar_navigationIcon = 20;
    public static final int Toolbar_popupTheme = 9;
    public static final int Toolbar_subtitle = 3;
    public static final int Toolbar_subtitleTextAppearance = 11;
    public static final int Toolbar_subtitleTextColor = 24;
    public static final int Toolbar_title = 2;
    public static final int Toolbar_titleMarginBottom = 16;
    public static final int Toolbar_titleMarginEnd = 14;
    public static final int Toolbar_titleMarginStart = 13;
    public static final int Toolbar_titleMarginTop = 15;
    public static final int Toolbar_titleMargins = 12;
    public static final int Toolbar_titleTextAppearance = 10;
    public static final int Toolbar_titleTextColor = 23;
    public static final int[] UnderlinePageIndicator;
    public static final int UnderlinePageIndicator_android_background = 0;
    public static final int UnderlinePageIndicator_fadeDelay = 3;
    public static final int UnderlinePageIndicator_fadeLength = 4;
    public static final int UnderlinePageIndicator_fades = 2;
    public static final int UnderlinePageIndicator_selectedColor = 1;
    public static final int[] View;
    public static final int[] ViewBackgroundHelper;
    public static final int ViewBackgroundHelper_android_background = 0;
    public static final int ViewBackgroundHelper_backgroundTint = 1;
    public static final int ViewBackgroundHelper_backgroundTintMode = 2;
    public static final int[] ViewPagerIndicator;
    public static final int ViewPagerIndicator_vpiCirclePageIndicatorStyle = 0;
    public static final int ViewPagerIndicator_vpiIconPageIndicatorStyle = 1;
    public static final int ViewPagerIndicator_vpiLinePageIndicatorStyle = 2;
    public static final int ViewPagerIndicator_vpiTabPageIndicatorStyle = 4;
    public static final int ViewPagerIndicator_vpiTitlePageIndicatorStyle = 3;
    public static final int ViewPagerIndicator_vpiUnderlinePageIndicatorStyle = 5;
    public static final int[] ViewStubCompat;
    public static final int ViewStubCompat_android_id = 0;
    public static final int ViewStubCompat_android_inflatedId = 2;
    public static final int ViewStubCompat_android_layout = 1;
    public static final int View_android_focusable = 1;
    public static final int View_android_theme = 0;
    public static final int View_paddingEnd = 3;
    public static final int View_paddingStart = 2;
    public static final int View_theme = 4;
    public static final int[] WalletFragmentOptions;
    public static final int WalletFragmentOptions_appTheme = 0;
    public static final int WalletFragmentOptions_environment = 1;
    public static final int WalletFragmentOptions_fragmentMode = 3;
    public static final int WalletFragmentOptions_fragmentStyle = 2;
    public static final int[] WalletFragmentStyle;
    public static final int WalletFragmentStyle_buyButtonAppearance = 3;
    public static final int WalletFragmentStyle_buyButtonHeight = 0;
    public static final int WalletFragmentStyle_buyButtonText = 2;
    public static final int WalletFragmentStyle_buyButtonWidth = 1;
    public static final int WalletFragmentStyle_maskedWalletDetailsBackground = 6;
    public static final int WalletFragmentStyle_maskedWalletDetailsButtonBackground = 8;
    public static final int WalletFragmentStyle_maskedWalletDetailsButtonTextAppearance = 7;
    public static final int WalletFragmentStyle_maskedWalletDetailsHeaderTextAppearance = 5;
    public static final int WalletFragmentStyle_maskedWalletDetailsLogoImageType = 10;
    public static final int WalletFragmentStyle_maskedWalletDetailsLogoTextColor = 9;
    public static final int WalletFragmentStyle_maskedWalletDetailsTextAppearance = 4;
    public static final int[] WrapHeightSwipeDisableViewPager;
    public static final int WrapHeightSwipeDisableViewPager_swipeEnabled = 0;
    public static final int[] com_appboy_ui_inappmessage_AppboyInAppMessageButtonView;
    public static final int f1113x4a486ca5 = 0;
    public static final int[] com_appboy_ui_inappmessage_AppboyInAppMessageTextView;
    public static final int f1114xacd19e4a = 0;
    public static final int[] com_facebook_like_view;
    public static final int com_facebook_like_view_com_facebook_auxiliary_view_position = 4;
    public static final int com_facebook_like_view_com_facebook_foreground_color = 0;
    public static final int com_facebook_like_view_com_facebook_horizontal_alignment = 5;
    public static final int com_facebook_like_view_com_facebook_object_id = 1;
    public static final int com_facebook_like_view_com_facebook_object_type = 2;
    public static final int com_facebook_like_view_com_facebook_style = 3;
    public static final int[] com_facebook_login_view;
    public static final int com_facebook_login_view_com_facebook_confirm_logout = 0;
    public static final int com_facebook_login_view_com_facebook_login_text = 1;
    public static final int com_facebook_login_view_com_facebook_logout_text = 2;
    public static final int com_facebook_login_view_com_facebook_tooltip_mode = 3;
    public static final int[] com_facebook_profile_picture_view;
    public static final int com_facebook_profile_picture_view_com_facebook_is_cropped = 1;
    public static final int com_facebook_profile_picture_view_com_facebook_preset_size = 0;

    static {
        ActionBar = new int[]{com.etsy.android.lib.R.height, com.etsy.android.lib.R.title, com.etsy.android.lib.R.navigationMode, com.etsy.android.lib.R.displayOptions, com.etsy.android.lib.R.subtitle, com.etsy.android.lib.R.titleTextStyle, com.etsy.android.lib.R.subtitleTextStyle, com.etsy.android.lib.R.icon, com.etsy.android.lib.R.logo, com.etsy.android.lib.R.divider, com.etsy.android.lib.R.background, com.etsy.android.lib.R.backgroundStacked, com.etsy.android.lib.R.backgroundSplit, com.etsy.android.lib.R.customNavigationLayout, com.etsy.android.lib.R.homeLayout, com.etsy.android.lib.R.progressBarStyle, com.etsy.android.lib.R.indeterminateProgressStyle, com.etsy.android.lib.R.progressBarPadding, com.etsy.android.lib.R.itemPadding, com.etsy.android.lib.R.hideOnContentScroll, com.etsy.android.lib.R.contentInsetStart, com.etsy.android.lib.R.contentInsetEnd, com.etsy.android.lib.R.contentInsetLeft, com.etsy.android.lib.R.contentInsetRight, com.etsy.android.lib.R.elevation, com.etsy.android.lib.R.popupTheme, com.etsy.android.lib.R.homeAsUpIndicator};
        int[] iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
        iArr[com_facebook_login_view_com_facebook_confirm_logout] = 16842931;
        ActionBarLayout = iArr;
        iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
        iArr[com_facebook_login_view_com_facebook_confirm_logout] = 16843071;
        ActionMenuItemView = iArr;
        ActionMenuView = new int[com_facebook_login_view_com_facebook_confirm_logout];
        ActionMode = new int[]{com.etsy.android.lib.R.height, com.etsy.android.lib.R.titleTextStyle, com.etsy.android.lib.R.subtitleTextStyle, com.etsy.android.lib.R.background, com.etsy.android.lib.R.backgroundSplit, com.etsy.android.lib.R.closeItemLayout};
        ActivityChooserView = new int[]{com.etsy.android.lib.R.initialActivityCount, com.etsy.android.lib.R.expandActivityOverflowButtonDrawable};
        AdsAttrs = new int[]{com.etsy.android.lib.R.adSize, com.etsy.android.lib.R.adSizes, com.etsy.android.lib.R.adUnitId};
        AlertDialog = new int[]{16842994, com.etsy.android.lib.R.buttonPanelSideLayout, com.etsy.android.lib.R.listLayout, com.etsy.android.lib.R.multiChoiceItemLayout, com.etsy.android.lib.R.singleChoiceItemLayout, com.etsy.android.lib.R.listItemLayout};
        AppBarLayout = new int[]{16842964, com.etsy.android.lib.R.elevation, com.etsy.android.lib.R.expanded};
        AppBarLayout_LayoutParams = new int[]{com.etsy.android.lib.R.layout_scrollFlags, com.etsy.android.lib.R.layout_scrollInterpolator};
        AppCompatImageView = new int[]{16843033, com.etsy.android.lib.R.srcCompat};
        AppCompatTextView = new int[]{16842804, com.etsy.android.lib.R.textAllCaps};
        AppCompatTheme = new int[]{16842839, 16842926, com.etsy.android.lib.R.windowActionBar, com.etsy.android.lib.R.windowNoTitle, com.etsy.android.lib.R.windowActionBarOverlay, com.etsy.android.lib.R.windowActionModeOverlay, com.etsy.android.lib.R.windowFixedWidthMajor, com.etsy.android.lib.R.windowFixedHeightMinor, com.etsy.android.lib.R.windowFixedWidthMinor, com.etsy.android.lib.R.windowFixedHeightMajor, com.etsy.android.lib.R.windowMinWidthMajor, com.etsy.android.lib.R.windowMinWidthMinor, com.etsy.android.lib.R.actionBarTabStyle, com.etsy.android.lib.R.actionBarTabBarStyle, com.etsy.android.lib.R.actionBarTabTextStyle, com.etsy.android.lib.R.actionOverflowButtonStyle, com.etsy.android.lib.R.actionOverflowMenuStyle, com.etsy.android.lib.R.actionBarPopupTheme, com.etsy.android.lib.R.actionBarStyle, com.etsy.android.lib.R.actionBarSplitStyle, com.etsy.android.lib.R.actionBarTheme, com.etsy.android.lib.R.actionBarWidgetTheme, com.etsy.android.lib.R.actionBarSize, com.etsy.android.lib.R.actionBarDivider, com.etsy.android.lib.R.actionBarItemBackground, com.etsy.android.lib.R.actionMenuTextAppearance, com.etsy.android.lib.R.actionMenuTextColor, com.etsy.android.lib.R.actionModeStyle, com.etsy.android.lib.R.actionModeCloseButtonStyle, com.etsy.android.lib.R.actionModeBackground, com.etsy.android.lib.R.actionModeSplitBackground, com.etsy.android.lib.R.actionModeCloseDrawable, com.etsy.android.lib.R.actionModeCutDrawable, com.etsy.android.lib.R.actionModeCopyDrawable, com.etsy.android.lib.R.actionModePasteDrawable, com.etsy.android.lib.R.actionModeSelectAllDrawable, com.etsy.android.lib.R.actionModeShareDrawable, com.etsy.android.lib.R.actionModeFindDrawable, com.etsy.android.lib.R.actionModeWebSearchDrawable, com.etsy.android.lib.R.actionModePopupWindowStyle, com.etsy.android.lib.R.textAppearanceLargePopupMenu, com.etsy.android.lib.R.textAppearanceSmallPopupMenu, com.etsy.android.lib.R.dialogTheme, com.etsy.android.lib.R.dialogPreferredPadding, com.etsy.android.lib.R.listDividerAlertDialog, com.etsy.android.lib.R.actionDropDownStyle, com.etsy.android.lib.R.dropdownListPreferredItemHeight, com.etsy.android.lib.R.spinnerDropDownItemStyle, com.etsy.android.lib.R.homeAsUpIndicator, com.etsy.android.lib.R.actionButtonStyle, com.etsy.android.lib.R.buttonBarStyle, com.etsy.android.lib.R.buttonBarButtonStyle, com.etsy.android.lib.R.selectableItemBackground, com.etsy.android.lib.R.selectableItemBackgroundBorderless, com.etsy.android.lib.R.borderlessButtonStyle, com.etsy.android.lib.R.dividerVertical, com.etsy.android.lib.R.dividerHorizontal, com.etsy.android.lib.R.activityChooserViewStyle, com.etsy.android.lib.R.toolbarStyle, com.etsy.android.lib.R.toolbarNavigationButtonStyle, com.etsy.android.lib.R.popupMenuStyle, com.etsy.android.lib.R.popupWindowStyle, com.etsy.android.lib.R.editTextColor, com.etsy.android.lib.R.editTextBackground, com.etsy.android.lib.R.imageButtonStyle, com.etsy.android.lib.R.textAppearanceSearchResultTitle, com.etsy.android.lib.R.textAppearanceSearchResultSubtitle, com.etsy.android.lib.R.textColorSearchUrl, com.etsy.android.lib.R.searchViewStyle, com.etsy.android.lib.R.listPreferredItemHeight, com.etsy.android.lib.R.listPreferredItemHeightSmall, com.etsy.android.lib.R.listPreferredItemHeightLarge, com.etsy.android.lib.R.listPreferredItemPaddingLeft, com.etsy.android.lib.R.listPreferredItemPaddingRight, com.etsy.android.lib.R.dropDownListViewStyle, com.etsy.android.lib.R.listPopupWindowStyle, com.etsy.android.lib.R.textAppearanceListItem, com.etsy.android.lib.R.textAppearanceListItemSmall, com.etsy.android.lib.R.panelBackground, com.etsy.android.lib.R.panelMenuListWidth, com.etsy.android.lib.R.panelMenuListTheme, com.etsy.android.lib.R.listChoiceBackgroundIndicator, com.etsy.android.lib.R.colorPrimary, com.etsy.android.lib.R.colorPrimaryDark, com.etsy.android.lib.R.colorAccent, com.etsy.android.lib.R.colorControlNormal, com.etsy.android.lib.R.colorControlActivated, com.etsy.android.lib.R.colorControlHighlight, com.etsy.android.lib.R.colorButtonNormal, com.etsy.android.lib.R.colorSwitchThumbNormal, com.etsy.android.lib.R.controlBackground, com.etsy.android.lib.R.alertDialogStyle, com.etsy.android.lib.R.alertDialogButtonGroupStyle, com.etsy.android.lib.R.alertDialogCenterButtons, com.etsy.android.lib.R.alertDialogTheme, com.etsy.android.lib.R.textColorAlertDialogListItem, com.etsy.android.lib.R.buttonBarPositiveButtonStyle, com.etsy.android.lib.R.buttonBarNegativeButtonStyle, com.etsy.android.lib.R.buttonBarNeutralButtonStyle, com.etsy.android.lib.R.autoCompleteTextViewStyle, com.etsy.android.lib.R.buttonStyle, com.etsy.android.lib.R.buttonStyleSmall, com.etsy.android.lib.R.checkboxStyle, com.etsy.android.lib.R.checkedTextViewStyle, com.etsy.android.lib.R.editTextStyle, com.etsy.android.lib.R.radioButtonStyle, com.etsy.android.lib.R.ratingBarStyle, com.etsy.android.lib.R.ratingBarStyleIndicator, com.etsy.android.lib.R.ratingBarStyleSmall, com.etsy.android.lib.R.seekBarStyle, com.etsy.android.lib.R.spinnerStyle, com.etsy.android.lib.R.switchStyle};
        AppDataSearch = new int[com_facebook_login_view_com_facebook_confirm_logout];
        BaseSplitView = new int[]{com.etsy.android.lib.R.empty_layout, com.etsy.android.lib.R.no_internet_layout, com.etsy.android.lib.R.side_panel_fraction};
        BottomSheetBehavior_Params = new int[]{com.etsy.android.lib.R.behavior_peekHeight, com.etsy.android.lib.R.behavior_hideable};
        iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
        iArr[com_facebook_login_view_com_facebook_confirm_logout] = com.etsy.android.lib.R.allowStacking;
        ButtonBarLayout = iArr;
        iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
        iArr[com_facebook_login_view_com_facebook_confirm_logout] = com.etsy.android.lib.R.tabWidgetBackground;
        CardTabView = iArr;
        CardView = new int[]{16843071, 16843072, com.etsy.android.lib.R.cardBackgroundColor, com.etsy.android.lib.R.cardCornerRadius, com.etsy.android.lib.R.cardElevation, com.etsy.android.lib.R.cardMaxElevation, com.etsy.android.lib.R.cardUseCompatPadding, com.etsy.android.lib.R.cardPreventCornerOverlap, com.etsy.android.lib.R.contentPadding, com.etsy.android.lib.R.contentPaddingLeft, com.etsy.android.lib.R.contentPaddingRight, com.etsy.android.lib.R.contentPaddingTop, com.etsy.android.lib.R.contentPaddingBottom};
        CharacterCounterView = new int[]{com.etsy.android.lib.R.maxChars, com.etsy.android.lib.R.format};
        CirclePageIndicator = new int[]{16842948, 16842964, com.etsy.android.lib.R.centered, com.etsy.android.lib.R.strokeWidth, com.etsy.android.lib.R.fillColor, com.etsy.android.lib.R.pageColor, com.etsy.android.lib.R.radius, com.etsy.android.lib.R.snap, com.etsy.android.lib.R.strokeColor};
        CollapsingAppBarLayout_LayoutParams = new int[]{com.etsy.android.lib.R.layout_collapseMode, com.etsy.android.lib.R.layout_collapseParallaxMultiplier};
        CollapsingToolbarLayout = new int[]{com.etsy.android.lib.R.title, com.etsy.android.lib.R.expandedTitleMargin, com.etsy.android.lib.R.expandedTitleMarginStart, com.etsy.android.lib.R.expandedTitleMarginTop, com.etsy.android.lib.R.expandedTitleMarginEnd, com.etsy.android.lib.R.expandedTitleMarginBottom, com.etsy.android.lib.R.expandedTitleTextAppearance, com.etsy.android.lib.R.collapsedTitleTextAppearance, com.etsy.android.lib.R.contentScrim, com.etsy.android.lib.R.statusBarScrim, com.etsy.android.lib.R.toolbarId, com.etsy.android.lib.R.collapsedTitleGravity, com.etsy.android.lib.R.expandedTitleGravity, com.etsy.android.lib.R.titleEnabled};
        CompoundButton = new int[]{16843015, com.etsy.android.lib.R.buttonTint, com.etsy.android.lib.R.buttonTintMode};
        CoordinatorLayout = new int[]{com.etsy.android.lib.R.keylines, com.etsy.android.lib.R.statusBarBackground};
        CoordinatorLayout_LayoutParams = new int[]{16842931, com.etsy.android.lib.R.layout_behavior, com.etsy.android.lib.R.layout_anchor, com.etsy.android.lib.R.layout_keyline, com.etsy.android.lib.R.layout_anchorGravity};
        Corpus = new int[]{2130772283, 2130772284, 2130772285, 2130772286, 2130772287, 2130772288, 2130772289};
        iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
        iArr[com_facebook_login_view_com_facebook_confirm_logout] = 2130772290;
        CustomWalletTheme = iArr;
        DesignTheme = new int[]{com.etsy.android.lib.R.bottomSheetDialogTheme, com.etsy.android.lib.R.bottomSheetStyle, com.etsy.android.lib.R.textColorError};
        DiagonalStrikeImageView = new int[]{com.etsy.android.lib.R.diagonalLineColor, com.etsy.android.lib.R.diagonalLineWidth};
        DrawerArrowToggle = new int[]{com.etsy.android.lib.R.color, com.etsy.android.lib.R.spinBars, com.etsy.android.lib.R.drawableSize, com.etsy.android.lib.R.gapBetweenBars, com.etsy.android.lib.R.arrowHeadLength, com.etsy.android.lib.R.arrowShaftLength, com.etsy.android.lib.R.barLength, com.etsy.android.lib.R.thickness};
        iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
        iArr[com_facebook_login_view_com_facebook_confirm_logout] = com.etsy.android.lib.R.tabLayout;
        EtsyTabView = iArr;
        FeatureParam = new int[]{2130772305, 2130772306};
        iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
        iArr[com_facebook_login_view_com_facebook_confirm_logout] = 2130772307;
        FindsCardView = iArr;
        FloatingActionButton = new int[]{com.etsy.android.lib.R.elevation, com.etsy.android.lib.R.rippleColor, com.etsy.android.lib.R.fabSize, com.etsy.android.lib.R.pressedTranslationZ, com.etsy.android.lib.R.borderWidth, com.etsy.android.lib.R.useCompatPadding, com.etsy.android.lib.R.backgroundTint, com.etsy.android.lib.R.backgroundTintMode};
        FlowLayout = new int[]{com.etsy.android.lib.R.horizontalSpacing, com.etsy.android.lib.R.verticalSpacing};
        iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
        iArr[com_facebook_login_view_com_facebook_confirm_logout] = com.etsy.android.lib.R.layout_breakLine;
        FlowLayout_LayoutParams = iArr;
        iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
        iArr[com_facebook_login_view_com_facebook_confirm_logout] = com.etsy.android.lib.R.foreground;
        ForegroundImageView = iArr;
        ForegroundLinearLayout = new int[]{16843017, 16843264, com.etsy.android.lib.R.foregroundInsidePadding};
        iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
        iArr[com_facebook_login_view_com_facebook_confirm_logout] = com.etsy.android.lib.R.imageAspect;
        FullImageView = iArr;
        GlobalSearch = new int[]{2130772319, 2130772320, 2130772321, 2130772322, 2130772323, 2130772324};
        iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
        iArr[com_facebook_login_view_com_facebook_confirm_logout] = 2130772325;
        GlobalSearchCorpus = iArr;
        GlobalSearchSection = new int[]{2130772326, 2130772327};
        GridLayout = new int[]{com.etsy.android.lib.R.orientation, com.etsy.android.lib.R.rowCount, com.etsy.android.lib.R.columnCount, com.etsy.android.lib.R.useDefaultMargins, com.etsy.android.lib.R.alignmentMode, com.etsy.android.lib.R.rowOrderPreserved, com.etsy.android.lib.R.columnOrderPreserved};
        GridLayout_Layout = new int[]{16842996, 16842997, 16842998, 16842999, 16843000, 16843001, 16843002, com.etsy.android.lib.R.layout_row, com.etsy.android.lib.R.layout_rowSpan, com.etsy.android.lib.R.layout_rowWeight, com.etsy.android.lib.R.layout_column, com.etsy.android.lib.R.layout_columnSpan, com.etsy.android.lib.R.layout_columnWeight, com.etsy.android.lib.R.layout_gravity};
        IMECorpus = new int[]{2130772342, 2130772343, 2130772344, 2130772345, 2130772346, 2130772347};
        IconView = new int[]{com.etsy.android.lib.R.iconChar, com.etsy.android.lib.R.gravity, com.etsy.android.lib.R.iconColor, com.etsy.android.lib.R.alpha, com.etsy.android.lib.R.hasSelector};
        iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
        iArr[com_facebook_login_view_com_facebook_confirm_logout] = com.etsy.android.lib.R.attachmentPadding;
        ImageAttachmentLayout = iArr;
        ImageViewWithAspectRatio = new int[]{com.etsy.android.lib.R.heightRatio, com.etsy.android.lib.R.doMaintainAspect};
        iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
        iArr[com_facebook_login_view_com_facebook_confirm_logout] = com.etsy.android.lib.R.img;
        LazyNativeAssetImageView = iArr;
        LinePageIndicator = new int[]{16842964, com.etsy.android.lib.R.centered, com.etsy.android.lib.R.selectedColor, com.etsy.android.lib.R.strokeWidth, com.etsy.android.lib.R.unselectedColor, com.etsy.android.lib.R.lineWidth, com.etsy.android.lib.R.gapWidth};
        LinearLayoutCompat = new int[]{16842927, 16842948, 16843046, 16843047, 16843048, com.etsy.android.lib.R.divider, com.etsy.android.lib.R.measureWithLargestChild, com.etsy.android.lib.R.showDividers, com.etsy.android.lib.R.dividerPadding};
        LinearLayoutCompat_Layout = new int[]{16842931, 16842996, 16842997, 16843137};
        ListPopupWindow = new int[]{16843436, 16843437};
        LoadingImageView = new int[]{com.etsy.android.lib.R.imageAspectRatioAdjust, com.etsy.android.lib.R.imageAspectRatio, com.etsy.android.lib.R.circleCrop};
        MachineTranslationOneClickView = new int[]{com.etsy.android.lib.R.textSize, com.etsy.android.lib.R.inactiveButtonColor, com.etsy.android.lib.R.activeButtonColor, com.etsy.android.lib.R.disclaimerText};
        MapAttrs = new int[]{com.etsy.android.lib.R.mapType, com.etsy.android.lib.R.cameraBearing, com.etsy.android.lib.R.cameraTargetLat, com.etsy.android.lib.R.cameraTargetLng, com.etsy.android.lib.R.cameraTilt, com.etsy.android.lib.R.cameraZoom, com.etsy.android.lib.R.liteMode, com.etsy.android.lib.R.uiCompass, com.etsy.android.lib.R.uiRotateGestures, com.etsy.android.lib.R.uiScrollGestures, com.etsy.android.lib.R.uiTiltGestures, com.etsy.android.lib.R.uiZoomControls, com.etsy.android.lib.R.uiZoomGestures, com.etsy.android.lib.R.useViewLifecycle, com.etsy.android.lib.R.zOrderOnTop, com.etsy.android.lib.R.uiMapToolbar, com.etsy.android.lib.R.ambientEnabled};
        iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
        iArr[com_facebook_login_view_com_facebook_confirm_logout] = com.etsy.android.lib.R.maxWidth;
        MaxWidthLayout = iArr;
        MenuGroup = new int[]{16842766, 16842960, 16843156, 16843230, 16843231, 16843232};
        MenuItem = new int[]{16842754, 16842766, 16842960, 16843014, 16843156, 16843230, 16843231, 16843233, 16843234, 16843235, 16843236, 16843237, 16843375, com.etsy.android.lib.R.showAsAction, com.etsy.android.lib.R.actionLayout, com.etsy.android.lib.R.actionViewClass, com.etsy.android.lib.R.actionProviderClass};
        MenuView = new int[]{16842926, 16843052, 16843053, 16843054, 16843055, 16843056, 16843057, com.etsy.android.lib.R.preserveIconSpacing};
        NavigationView = new int[]{16842964, 16842973, 16843039, com.etsy.android.lib.R.elevation, com.etsy.android.lib.R.menu, com.etsy.android.lib.R.itemIconTint, com.etsy.android.lib.R.itemTextColor, com.etsy.android.lib.R.itemBackground, com.etsy.android.lib.R.itemTextAppearance, com.etsy.android.lib.R.headerLayout};
        PopupWindow = new int[]{16843126, com.etsy.android.lib.R.overlapAnchor};
        iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
        iArr[com_facebook_login_view_com_facebook_confirm_logout] = com.etsy.android.lib.R.state_above_anchor;
        PopupWindowBackgroundState = iArr;
        ProgressButton = new int[]{com.etsy.android.lib.R.text, com.etsy.android.lib.R.drawableLeft, com.etsy.android.lib.R.textStyleResource, com.etsy.android.lib.R.activityIndicatorDrawable};
        RangedProgressBar = new int[]{com.etsy.android.lib.R.waypointValues, com.etsy.android.lib.R.waypointLabels, com.etsy.android.lib.R.waypointLevels};
        iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
        iArr[com_facebook_login_view_com_facebook_confirm_logout] = com.etsy.android.lib.R.starSize;
        RatingStarBar = iArr;
        iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
        iArr[com_facebook_login_view_com_facebook_confirm_logout] = com.etsy.android.lib.R.state_read;
        ReadState = iArr;
        RecyclerView = new int[]{16842948, com.etsy.android.lib.R.layoutManager, com.etsy.android.lib.R.spanCount, com.etsy.android.lib.R.reverseLayout, com.etsy.android.lib.R.stackFromEnd};
        RoundStrokedCheckBox = new int[]{com.etsy.android.lib.R.unselectedStrokeWidth, com.etsy.android.lib.R.unselectedStrokeColor, com.etsy.android.lib.R.selectedBackgroundColor, com.etsy.android.lib.R.selectedDrawableColor, com.etsy.android.lib.R.selectedDrawableInset};
        iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
        iArr[com_facebook_login_view_com_facebook_confirm_logout] = com.etsy.android.lib.R.insetForeground;
        ScrimInsetsFrameLayout = iArr;
        iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
        iArr[com_facebook_login_view_com_facebook_confirm_logout] = com.etsy.android.lib.R.behavior_overlapTop;
        ScrollingViewBehavior_Params = iArr;
        SearchView = new int[]{16842970, 16843039, 16843296, 16843364, com.etsy.android.lib.R.layout, com.etsy.android.lib.R.iconifiedByDefault, com.etsy.android.lib.R.queryHint, com.etsy.android.lib.R.defaultQueryHint, com.etsy.android.lib.R.closeIcon, com.etsy.android.lib.R.goIcon, com.etsy.android.lib.R.searchIcon, com.etsy.android.lib.R.searchHintIcon, com.etsy.android.lib.R.voiceIcon, com.etsy.android.lib.R.commitIcon, com.etsy.android.lib.R.suggestionRowLayout, com.etsy.android.lib.R.queryBackground, com.etsy.android.lib.R.submitBackground};
        Section = new int[]{2130772433, 2130772434, 2130772435, 2130772436, 2130772437, 2130772438, 2130772439};
        iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
        iArr[com_facebook_login_view_com_facebook_confirm_logout] = 2130772440;
        SectionFeature = iArr;
        SignInButton = new int[]{com.etsy.android.lib.R.buttonSize, com.etsy.android.lib.R.colorScheme, com.etsy.android.lib.R.scopeUris};
        SnackbarLayout = new int[]{16843039, com.etsy.android.lib.R.elevation, com.etsy.android.lib.R.maxActionInlineWidth};
        Spinner = new int[]{16842930, 16843126, 16843131, 16843362, com.etsy.android.lib.R.popupTheme};
        StructuredShopPoliciesView = new int[]{com.etsy.android.lib.R.editMode, com.etsy.android.lib.R.structuredPoliciesSubheadStyle, com.etsy.android.lib.R.structuredPoliciesTextStyle, com.etsy.android.lib.R.structuredPoliciesTextLightStyle};
        SwitchCompat = new int[]{16843044, 16843045, 16843074, com.etsy.android.lib.R.track, com.etsy.android.lib.R.thumbTextPadding, com.etsy.android.lib.R.switchTextAppearance, com.etsy.android.lib.R.switchMinWidth, com.etsy.android.lib.R.switchPadding, com.etsy.android.lib.R.splitTrack, com.etsy.android.lib.R.showText};
        SwitchToggle = new int[]{16843044, 16843045};
        TabItem = new int[]{16842754, 16842994, 16843087};
        TabLayout = new int[]{com.etsy.android.lib.R.tabIndicatorColor, com.etsy.android.lib.R.tabIndicatorHeight, com.etsy.android.lib.R.tabContentStart, com.etsy.android.lib.R.tabBackground, com.etsy.android.lib.R.tabMode, com.etsy.android.lib.R.tabGravity, com.etsy.android.lib.R.tabMinWidth, com.etsy.android.lib.R.tabMaxWidth, com.etsy.android.lib.R.tabTextAppearance, com.etsy.android.lib.R.tabTextColor, com.etsy.android.lib.R.tabSelectedTextColor, com.etsy.android.lib.R.tabPaddingStart, com.etsy.android.lib.R.tabPaddingTop, com.etsy.android.lib.R.tabPaddingEnd, com.etsy.android.lib.R.tabPaddingBottom, com.etsy.android.lib.R.tabPadding};
        iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
        iArr[com_facebook_login_view_com_facebook_confirm_logout] = com.etsy.android.lib.R.editable;
        TaggableImageView = iArr;
        TextAppearance = new int[]{16842901, 16842902, 16842903, 16842904, 16843105, 16843106, 16843107, 16843108, com.etsy.android.lib.R.textAllCaps};
        TextInputLayout = new int[]{16842906, 16843088, com.etsy.android.lib.R.hintTextAppearance, com.etsy.android.lib.R.hintEnabled, com.etsy.android.lib.R.errorEnabled, com.etsy.android.lib.R.errorTextAppearance, com.etsy.android.lib.R.counterEnabled, com.etsy.android.lib.R.counterMaxLength, com.etsy.android.lib.R.counterTextAppearance, com.etsy.android.lib.R.counterOverflowTextAppearance, com.etsy.android.lib.R.hintAnimationEnabled};
        TitlePageIndicator = new int[]{16842901, 16842904, 16842964, com.etsy.android.lib.R.selectedColor, com.etsy.android.lib.R.clipPadding, com.etsy.android.lib.R.footerColor, com.etsy.android.lib.R.footerLineHeight, com.etsy.android.lib.R.footerIndicatorStyle, com.etsy.android.lib.R.footerIndicatorHeight, com.etsy.android.lib.R.footerIndicatorUnderlinePadding, com.etsy.android.lib.R.footerPadding, com.etsy.android.lib.R.linePosition, com.etsy.android.lib.R.selectedBold, com.etsy.android.lib.R.titlePadding, com.etsy.android.lib.R.topPadding};
        Toolbar = new int[]{16842927, 16843072, com.etsy.android.lib.R.title, com.etsy.android.lib.R.subtitle, com.etsy.android.lib.R.logo, com.etsy.android.lib.R.contentInsetStart, com.etsy.android.lib.R.contentInsetEnd, com.etsy.android.lib.R.contentInsetLeft, com.etsy.android.lib.R.contentInsetRight, com.etsy.android.lib.R.popupTheme, com.etsy.android.lib.R.titleTextAppearance, com.etsy.android.lib.R.subtitleTextAppearance, com.etsy.android.lib.R.titleMargins, com.etsy.android.lib.R.titleMarginStart, com.etsy.android.lib.R.titleMarginEnd, com.etsy.android.lib.R.titleMarginTop, com.etsy.android.lib.R.titleMarginBottom, com.etsy.android.lib.R.maxButtonHeight, com.etsy.android.lib.R.collapseIcon, com.etsy.android.lib.R.collapseContentDescription, com.etsy.android.lib.R.navigationIcon, com.etsy.android.lib.R.navigationContentDescription, com.etsy.android.lib.R.logoDescription, com.etsy.android.lib.R.titleTextColor, com.etsy.android.lib.R.subtitleTextColor};
        UnderlinePageIndicator = new int[]{16842964, com.etsy.android.lib.R.selectedColor, com.etsy.android.lib.R.fades, com.etsy.android.lib.R.fadeDelay, com.etsy.android.lib.R.fadeLength};
        View = new int[]{16842752, 16842970, com.etsy.android.lib.R.paddingStart, com.etsy.android.lib.R.paddingEnd, com.etsy.android.lib.R.theme};
        ViewBackgroundHelper = new int[]{16842964, com.etsy.android.lib.R.backgroundTint, com.etsy.android.lib.R.backgroundTintMode};
        ViewPagerIndicator = new int[]{com.etsy.android.lib.R.vpiCirclePageIndicatorStyle, com.etsy.android.lib.R.vpiIconPageIndicatorStyle, com.etsy.android.lib.R.vpiLinePageIndicatorStyle, com.etsy.android.lib.R.vpiTitlePageIndicatorStyle, com.etsy.android.lib.R.vpiTabPageIndicatorStyle, com.etsy.android.lib.R.vpiUnderlinePageIndicatorStyle};
        ViewStubCompat = new int[]{16842960, 16842994, 16842995};
        WalletFragmentOptions = new int[]{2130772522, 2130772523, 2130772524, 2130772525};
        WalletFragmentStyle = new int[]{2130772526, 2130772527, 2130772528, 2130772529, 2130772530, 2130772531, 2130772532, 2130772533, 2130772534, 2130772535, 2130772536};
        iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
        iArr[com_facebook_login_view_com_facebook_confirm_logout] = com.etsy.android.lib.R.swipeEnabled;
        WrapHeightSwipeDisableViewPager = iArr;
        iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
        iArr[com_facebook_login_view_com_facebook_confirm_logout] = C0401R.attr.appboyInAppMessageCustomFontFile;
        com_appboy_ui_inappmessage_AppboyInAppMessageButtonView = iArr;
        iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
        iArr[com_facebook_login_view_com_facebook_confirm_logout] = C0401R.attr.appboyInAppMessageCustomFontFile;
        com_appboy_ui_inappmessage_AppboyInAppMessageTextView = iArr;
        com_facebook_like_view = new int[]{com.etsy.android.lib.R.com_facebook_foreground_color, com.etsy.android.lib.R.com_facebook_object_id, com.etsy.android.lib.R.com_facebook_object_type, com.etsy.android.lib.R.com_facebook_style, com.etsy.android.lib.R.com_facebook_auxiliary_view_position, com.etsy.android.lib.R.com_facebook_horizontal_alignment};
        com_facebook_login_view = new int[]{com.etsy.android.lib.R.com_facebook_confirm_logout, com.etsy.android.lib.R.com_facebook_login_text, com.etsy.android.lib.R.com_facebook_logout_text, com.etsy.android.lib.R.com_facebook_tooltip_mode};
        com_facebook_profile_picture_view = new int[]{com.etsy.android.lib.R.com_facebook_preset_size, com.etsy.android.lib.R.com_facebook_is_cropped};
    }
}
